version: '3.8'

services:
  behemoth_fastapi:
    build: .
    command: bash -c 'while !</dev/tcp/behemoth_db/5432; do sleep 1; done; alembic upgrade head; uvicorn app.main:app --host 0.0.0.0 --port 8000'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=true
      - USER_SECRET_KEY=${SECRET_KEY}
      - OAUTH2_STATE_EXPIRE_MIN=${OAUTH2_STATE_EXPIRE_MIN}
      - REFRESH_TOKEN_EXPIRE_HOURS=${REFRESH_TOKEN_EXPIRE_HOURS}
      - ACCESS_TOKEN_EXPIRE_MINS=${ACCESS_TOKEN_EXPIRE_MINS}
      - MEDIA_DIR=${MEDIA_DIR}
      - CRIIPTO_VERIFY_DOMAIN=${CRIIPTO_VERIFY_DOMAIN}
      - CRIIPTO_VERIFY_CLIENT_ID=${CRIIPTO_VERIFY_CLIENT_ID}
      - CRIIPTO_VERIFY_CLIENT_SECRET=${CRIIPTO_VERIFY_CLIENT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_DATABASE_URL=postgresql+asyncpg://behemoth:backend@behemoth_db:5432/behemoth_db
    depends_on:
      - behemoth_db
    networks:
      - behemoth_network

  behemoth_db:
    image: postgres:15-alpine
    volumes:
      - behemoth_volume:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=behemoth
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=behemoth_db
    networks:
      - behemoth_network

volumes:
  behemoth_volume:


networks:
  behemoth_network:
